@BookApi_HostAddress = https://localhost:7197


POST {{BookApi_HostAddress}}/books
Content-Type: application/json

{
  "title":"Balladyna",
  "year":"1839",
  "authorId": "2"
}

###

POST {{BookApi_HostAddress}}/authors
Content-Type: application/json

{
    "FirstName":"Janek",
    "LastName":"Danonek"
}

###

GET {{BookApi_HostAddress}}/authors
